from __future__ import annotations

__all__ = ["EXPANSION_TRACE"]

# Expansion trace extracted from highest-scoring competitive replay (90650891, final bank: $191,624.00)
# Day 8 (Steps 169-192): First quadrant expansion (NE) & pasture/crop setup
# Day 12 (Steps 265-288): Second quadrant expansion (SW) & pasture/crop setup
EXPANSION_TRACE: dict[int, dict] = {
    169: {
        "farmer": ["PICKUP", "WHEAT", 5],
        "hands": [],
        "market": [
            ["SELL", "WOOL", 12],
            ["SELL", "FERTILIZER", 6],
            ["SELL", "WHEAT", 1],
            ["HIRE"],
            ["HIRE"],
            ["HIRE"],
            ["HIRE"],
            ["BUY_LAND"],
            ["BUY_ANIMAL", "SHEEP", 2],
            ["BUY_ANIMAL", "COW", 2],
        ],
    },
    170: {
        "farmer": ["FEED"],
        "hands": [["PICKUP", "COW", 2], ["NORTH"], ["NORTH"], ["WEST"]],
        "market": [
            ["HIRE"],
            ["HIRE"],
            ["BUY_PRODUCT", "WHEAT", 9],
            ["BUY_SEED", "STRAWBERRY", 8],
        ],
    },
    171: {
        "farmer": ["CARE"],
        "hands": [
            ["BUILD_PASTURE"],
            ["NORTH"],
            ["PICKUP", "WHEAT", 2],
            ["WEST"],
            ["NORTH"],
            ["NORTH"],
        ],
        "market": [["BUY_PRODUCT", "WHEAT", 1]],
    },
    172: {
        "farmer": ["WEST"],
        "hands": [
            ["PLACE", "COW"],
            ["WEST"],
            ["PICKUP", "SHEEP", 2],
            ["WEST"],
            ["NORTH"],
            ["NORTH"],
        ],
        "market": [],
    },
    173: {
        "farmer": ["FEED"],
        "hands": [
            ["EAST"],
            ["WEST"],
            ["NORTH"],
            ["WATER"],
            ["NORTH"],
            ["NORTH"],
        ],
        "market": [],
    },
    174: {
        "farmer": ["CARE"],
        "hands": [
            ["BUILD_PASTURE"],
            ["WATER"],
            ["BUILD_PASTURE"],
            ["WEST"],
            ["CARE"],
            ["BUILD_PASTURE"],
        ],
        "market": [["BUY_PRODUCT", "WHEAT", 1]],
    },
    175: {
        "farmer": ["WEST"],
        "hands": [
            ["PLACE", "COW"],
            ["WEST"],
            ["PLACE", "SHEEP"],
            ["WATER"],
            ["COLLECT_FERTILIZER"],
            ["EAST"],
        ],
        "market": [],
    },
    176: {
        "farmer": ["FEED"],
        "hands": [
            ["EAST"],
            ["WATER"],
            ["FEED"],
            ["NORTH"],
            ["WEST"],
            ["PLANT", "STRAWBERRY"],
        ],
        "market": [],
    },
    177: {
        "farmer": ["CARE"],
        "hands": [
            ["BUILD_PASTURE"],
            ["NORTH"],
            ["CARE"],
            ["WATER"],
            ["WATER"],
            ["WATER"],
        ],
        "market": [["SELL", "WHEAT", 2], ["BUY_PRODUCT", "WHEAT", 2]],
    },
    178: {
        "farmer": ["NORTH"],
        "hands": [["EAST"], ["WATER"], ["EAST"], ["NORTH"], ["WEST"], ["EAST"]],
        "market": [["SELL", "WHEAT", 2], ["BUY_PRODUCT", "WHEAT", 2]],
    },
    179: {
        "farmer": ["EAST"],
        "hands": [
            ["PLANT", "STRAWBERRY"],
            ["NORTH"],
            ["BUILD_PASTURE"],
            ["WATER"],
            ["WATER"],
            ["EAST"],
        ],
        "market": [["SELL", "WHEAT", 2], ["BUY_PRODUCT", "WHEAT", 2]],
    },
    180: {
        "farmer": ["FEED"],
        "hands": [
            ["WATER"],
            ["WATER"],
            ["PLACE", "SHEEP"],
            ["NORTH"],
            ["NORTH"],
            ["PLANT", "STRAWBERRY"],
        ],
        "market": [["SELL", "WHEAT", 2], ["BUY_PRODUCT", "WHEAT", 2]],
    },
    181: {
        "farmer": ["CARE"],
        "hands": [["EAST"], ["EAST"], ["FEED"], ["WATER"], ["EAST"], ["WATER"]],
        "market": [["SELL", "WHEAT", 3], ["BUY_PRODUCT", "WHEAT", 3]],
    },
    182: {
        "farmer": ["EAST"],
        "hands": [
            ["PLANT", "STRAWBERRY"],
            ["WATER"],
            ["CARE"],
            ["NORTH"],
            ["WATER"],
            ["SOUTH"],
        ],
        "market": [["SELL", "WHEAT", 4], ["BUY_PRODUCT", "WHEAT", 4]],
    },
    183: {
        "farmer": ["FEED"],
        "hands": [
            ["WATER"],
            ["EAST"],
            ["EAST"],
            ["WATER"],
            ["NORTH"],
            ["PLANT", "STRAWBERRY"],
        ],
        "market": [["SELL", "WHEAT", 4], ["BUY_PRODUCT", "WHEAT", 4]],
    },
    184: {
        "farmer": ["CARE"],
        "hands": [
            ["NORTH"],
            ["EAST"],
            ["PLANT", "STRAWBERRY"],
            ["EAST"],
            ["WATER"],
            ["WATER"],
        ],
        "market": [["SELL", "WHEAT", 5], ["BUY_PRODUCT", "WHEAT", 5]],
    },
    185: {
        "farmer": ["COLLECT_FERTILIZER"],
        "hands": [
            ["PLANT", "STRAWBERRY"],
            ["WATER"],
            ["WATER"],
            ["WATER"],
            ["SOUTH"],
            ["NORTH"],
        ],
        "market": [["SELL", "WHEAT", 5], ["BUY_PRODUCT", "WHEAT", 5]],
    },
    186: {
        "farmer": ["SOUTH"],
        "hands": [
            ["WATER"],
            ["NORTH"],
            ["NORTH"],
            ["EAST"],
            ["SOUTH"],
            ["EAST"],
        ],
        "market": [["SELL", "WHEAT", 5], ["BUY_PRODUCT", "WHEAT", 5]],
    },
    187: {
        "farmer": ["COLLECT_FERTILIZER"],
        "hands": [
            ["NORTH"],
            ["WATER"],
            ["PLANT", "STRAWBERRY"],
            ["WATER"],
            ["SOUTH"],
            ["PASS"],
        ],
        "market": [["SELL", "WHEAT", 5], ["BUY_PRODUCT", "WHEAT", 5]],
    },
    188: {
        "farmer": ["WEST"],
        "hands": [["PASS"], ["SOUTH"], ["WATER"], ["PASS"], ["PASS"], ["PASS"]],
        "market": [["SELL", "WHEAT", 5], ["BUY_PRODUCT", "WHEAT", 5]],
    },
    189: {
        "farmer": ["COLLECT_FERTILIZER"],
        "hands": [["PASS"], ["SOUTH"], ["PASS"], ["PASS"], ["PASS"], ["PASS"]],
        "market": [["SELL", "WHEAT", 5]],
    },
    190: {
        "farmer": ["WEST"],
        "hands": [["PASS"], ["SOUTH"], ["PASS"], ["PASS"], ["PASS"], ["PASS"]],
        "market": [],
    },
    191: {
        "farmer": ["COLLECT_FERTILIZER"],
        "hands": [["PASS"], ["WEST"], ["PASS"], ["PASS"], ["PASS"], ["PASS"]],
        "market": [],
    },
    192: {
        "farmer": ["NORTH"],
        "hands": [
            ["PASS"],
            ["COLLECT_FERTILIZER"],
            ["PASS"],
            ["PASS"],
            ["PASS"],
            ["PASS"],
        ],
        "market": [],
    },
    265: {
        "farmer": ["PICKUP", "WHEAT", 5],
        "hands": [],
        "market": [
            ["SELL", "MELON", 30],
            ["SELL", "FERTILIZER", 9],
            ["HIRE"],
            ["HIRE"],
            ["HIRE"],
            ["HIRE"],
            ["HIRE"],
            ["BUY_LAND"],
            ["BUY_ANIMAL", "SHEEP", 2],
            ["BUY_SEED", "MELON", 12],
        ],
    },
    266: {
        "farmer": ["DROP"],
        "hands": [
            ["PICKUP", "WHEAT", 4],
            ["PICKUP", "WHEAT", 2],
            ["WEST"],
            ["PICKUP", "WHEAT", 2],
            ["EAST"],
        ],
        "market": [
            ["HIRE"],
            ["HIRE"],
            ["HIRE"],
            ["HIRE"],
            ["HIRE"],
            ["BUY_SEED", "STRAWBERRY", 23],
        ],
    },
    267: {
        "farmer": ["PICKUP", "WHEAT", 4],
        "hands": [
            ["FEED"],
            ["PICKUP", "SHEEP", 2],
            ["SOUTH"],
            ["NORTH"],
            ["EAST"],
            ["WEST"],
            ["NORTH"],
            ["NORTH"],
            ["WEST"],
            ["NORTH"],
        ],
        "market": [
            ["HIRE"],
            ["HIRE"],
            ["HIRE"],
            ["HIRE"],
            ["BUY_PRODUCT", "WHEAT", 16],
        ],
    },
    268: {
        "farmer": ["FEED"],
        "hands": [
            ["CARE"],
            ["BUILD_PASTURE"],
            ["PLANT", "STRAWBERRY"],
            ["FEED"],
            ["EAST"],
            ["SOUTH"],
            ["NORTH"],
            ["EAST"],
            ["WEST"],
            ["WEST"],
            ["WEST"],
            ["NORTH"],
            ["NORTH"],
            ["NORTH"],
        ],
        "market": [["BUY_PRODUCT", "WHEAT", 1]],
    },
    269: {
        "farmer": ["CARE"],
        "hands": [
            ["EAST"],
            ["PLACE", "SHEEP"],
            ["WATER"],
            ["CARE"],
            ["WATER"],
            ["WATER"],
            ["NORTH"],
            ["EAST"],
            ["WEST"],
            ["WEST"],
            ["SOUTH"],
            ["NORTH"],
            ["NORTH"],
            ["NORTH"],
        ],
        "market": [["BUY_PRODUCT", "WHEAT", 2]],
    },
    270: {
        "farmer": ["WEST"],
        "hands": [
            ["FEED"],
            ["FEED"],
            ["WEST"],
            ["NORTH"],
            ["EAST"],
            ["SOUTH"],
            ["NORTH"],
            ["CARE"],
            ["WATER"],
            ["WEST"],
            ["SOUTH"],
            ["NORTH"],
            ["NORTH"],
            ["NORTH"],
        ],
        "market": [],
    },
    271: {
        "farmer": ["FEED"],
        "hands": [
            ["CARE"],
            ["CARE"],
            ["PLANT", "STRAWBERRY"],
            ["FEED"],
            ["WATER"],
            ["PLANT", "STRAWBERRY"],
            ["WATER"],
            ["COLLECT_FERTILIZER"],
            ["WEST"],
            ["WEST"],
            ["SOUTH"],
            ["WATER"],
            ["CARE"],
            ["NORTH"],
        ],
        "market": [["BUY_PRODUCT", "WHEAT", 2]],
    },
    272: {
        "farmer": ["CARE"],
        "hands": [
            ["NORTH"],
            ["WEST"],
            ["WATER"],
            ["CARE"],
            ["NORTH"],
            ["WATER"],
            ["EAST"],
            ["NORTH"],
            ["PLANT", "MELON"],
            ["WATER"],
            ["PLANT", "STRAWBERRY"],
            ["WEST"],
            ["COLLECT_FERTILIZER"],
            ["HARVEST"],
        ],
        "market": [["SELL", "WHEAT", 2], ["BUY_PRODUCT", "WHEAT", 2]],
    },
    273: {
        "farmer": ["WEST"],
        "hands": [
            ["FEED"],
            ["BUILD_PASTURE"],
            ["WEST"],
            ["COLLECT_FERTILIZER"],
            ["WATER"],
            ["WEST"],
            ["WATER"],
            ["WATER"],
            ["WATER"],
            ["EAST"],
            ["WATER"],
            ["PLANT", "MELON"],
            ["EAST"],
            ["PLANT", "MELON"],
        ],
        "market": [["SELL", "WHEAT", 2], ["BUY_PRODUCT", "WHEAT", 2]],
    },
    274: {
        "farmer": ["FEED"],
        "hands": [
            ["CARE"],
            ["PLACE", "SHEEP"],
            ["PLANT", "STRAWBERRY"],
            ["WEST"],
            ["NORTH"],
            ["PLANT", "STRAWBERRY"],
            ["EAST"],
            ["EAST"],
            ["NORTH"],
            ["EAST"],
            ["WEST"],
            ["WATER"],
            ["WATER"],
            ["WATER"],
        ],
        "market": [["SELL", "WHEAT", 3], ["BUY_PRODUCT", "WHEAT", 3]],
    },
    275: {
        "farmer": ["CARE"],
        "hands": [
            ["WEST"],
            ["FEED"],
            ["WATER"],
            ["PLANT", "MELON"],
            ["WEST"],
            ["WATER"],
            ["WATER"],
            ["WATER"],
            ["PLANT", "MELON"],
            ["CARE"],
            ["PLANT", "STRAWBERRY"],
            ["WEST"],
            ["EAST"],
            ["WEST"],
        ],
        "market": [["SELL", "WHEAT", 4], ["BUY_PRODUCT", "WHEAT", 4]],
    },
    276: {
        "farmer": ["NORTH"],
        "hands": [
            ["FEED"],
            ["CARE"],
            ["WEST"],
            ["WATER"],
            ["WATER"],
            ["WEST"],
            ["EAST"],
            ["PASS"],
            ["WATER"],
            ["EAST"],
            ["WATER"],
            ["PLANT", "MELON"],
            ["WATER"],
            ["WATER"],
        ],
        "market": [["SELL", "WHEAT", 5], ["BUY_PRODUCT", "WHEAT", 5]],
    },
    277: {
        "farmer": ["EAST"],
        "hands": [
            ["CARE"],
            ["WEST"],
            ["PLANT", "STRAWBERRY"],
            ["WEST"],
            ["NORTH"],
            ["PLANT", "STRAWBERRY"],
            ["WATER"],
            ["PASS"],
            ["NORTH"],
            ["COLLECT_FERTILIZER"],
            ["WEST"],
            ["WATER"],
            ["NORTH"],
            ["SOUTH"],
        ],
        "market": [["SELL", "WHEAT", 6], ["BUY_PRODUCT", "WHEAT", 6]],
    },
    278: {
        "farmer": ["FEED"],
        "hands": [
            ["COLLECT_FERTILIZER"],
            ["PLANT", "STRAWBERRY"],
            ["WATER"],
            ["WATER"],
            ["WATER"],
            ["WATER"],
            ["EAST"],
            ["PASS"],
            ["HARVEST"],
            ["SOUTH"],
            ["PLANT", "STRAWBERRY"],
            ["WEST"],
            ["WATER"],
            ["SOUTH"],
        ],
        "market": [["SELL", "WHEAT", 6], ["BUY_PRODUCT", "WHEAT", 6]],
    },
    279: {
        "farmer": ["COLLECT_FERTILIZER"],
        "hands": [
            ["SOUTH"],
            ["WATER"],
            ["WEST"],
            ["WEST"],
            ["PASS"],
            ["WEST"],
            ["WATER"],
            ["PASS"],
            ["PLANT", "MELON"],
            ["COLLECT_FERTILIZER"],
            ["WATER"],
            ["WATER"],
            ["PASS"],
            ["SOUTH"],
        ],
        "market": [["SELL", "WHEAT", 7], ["BUY_PRODUCT", "WHEAT", 7]],
    },
    280: {
        "farmer": ["WEST"],
        "hands": [
            ["COLLECT_FERTILIZER"],
            ["WEST"],
            ["PLANT", "STRAWBERRY"],
            ["PLANT", "MELON"],
            ["PASS"],
            ["PLANT", "STRAWBERRY"],
            ["PASS"],
            ["PASS"],
            ["WATER"],
            ["PASS"],
            ["SOUTH"],
            ["NORTH"],
            ["PASS"],
            ["SOUTH"],
        ],
        "market": [["SELL", "WHEAT", 7], ["BUY_PRODUCT", "WHEAT", 7]],
    },
    281: {
        "farmer": ["PLANT", "MELON"],
        "hands": [
            ["EAST"],
            ["PLANT", "STRAWBERRY"],
            ["WATER"],
            ["WATER"],
            ["PASS"],
            ["WATER"],
            ["PASS"],
            ["PASS"],
            ["NORTH"],
            ["WEST"],
            ["PLANT", "STRAWBERRY"],
            ["PLANT", "MELON"],
            ["PASS"],
            ["EAST"],
        ],
        "market": [["SELL", "WHEAT", 7], ["BUY_PRODUCT", "WHEAT", 7]],
    },
    282: {
        "farmer": ["WATER"],
        "hands": [
            ["COLLECT_FERTILIZER"],
            ["WATER"],
            ["SOUTH"],
            ["PASS"],
            ["PASS"],
            ["SOUTH"],
            ["PASS"],
            ["PASS"],
            ["PLANT", "MELON"],
            ["HARVEST"],
            ["WATER"],
            ["WATER"],
            ["PASS"],
            ["DROP"],
        ],
        "market": [
            ["SELL", "WHEAT", 7],
            ["SELL", "MELON", 6],
            ["BUY_PRODUCT", "WHEAT", 7],
        ],
    },
    283: {
        "farmer": ["SOUTH"],
        "hands": [
            ["NORTH"],
            ["WEST"],
            ["PLANT", "STRAWBERRY"],
            ["PASS"],
            ["PASS"],
            ["PLANT", "STRAWBERRY"],
            ["PASS"],
            ["PASS"],
            ["WATER"],
            ["EAST"],
            ["WEST"],
            ["EAST"],
            ["PASS"],
            ["PASS"],
        ],
        "market": [["SELL", "WHEAT", 7], ["BUY_PRODUCT", "WHEAT", 7]],
    },
    284: {
        "farmer": ["HARVEST"],
        "hands": [
            ["COLLECT_FERTILIZER"],
            ["PLANT", "STRAWBERRY"],
            ["WATER"],
            ["PASS"],
            ["PASS"],
            ["WATER"],
            ["PASS"],
            ["PASS"],
            ["NORTH"],
            ["DROP"],
            ["PLANT", "STRAWBERRY"],
            ["PLANT", "MELON"],
            ["PASS"],
            ["PASS"],
        ],
        "market": [
            ["SELL", "WHEAT", 7],
            ["SELL", "MILK", 3],
            ["BUY_PRODUCT", "WHEAT", 7],
        ],
    },
    285: {
        "farmer": ["COLLECT_FERTILIZER"],
        "hands": [
            ["PASS"],
            ["WATER"],
            ["SOUTH"],
            ["PASS"],
            ["PASS"],
            ["WEST"],
            ["PASS"],
            ["PASS"],
            ["WATER"],
            ["PASS"],
            ["WATER"],
            ["WATER"],
            ["PASS"],
            ["PASS"],
        ],
        "market": [["SELL", "WHEAT", 7], ["SELL", "FERTILIZER", 2]],
    },
    286: {
        "farmer": ["EAST"],
        "hands": [
            ["PASS"],
            ["SOUTH"],
            ["SOUTH"],
            ["PASS"],
            ["PASS"],
            ["PLANT", "STRAWBERRY"],
            ["PASS"],
            ["PASS"],
            ["SOUTH"],
            ["PASS"],
            ["EAST"],
            ["PASS"],
            ["PASS"],
            ["PASS"],
        ],
        "market": [],
    },
    287: {
        "farmer": ["COLLECT_FERTILIZER"],
        "hands": [
            ["PASS"],
            ["SOUTH"],
            ["EAST"],
            ["PASS"],
            ["PASS"],
            ["WATER"],
            ["PASS"],
            ["PASS"],
            ["SOUTH"],
            ["PASS"],
            ["EAST"],
            ["PASS"],
            ["PASS"],
            ["PASS"],
        ],
        "market": [],
    },
    288: {
        "farmer": ["EAST"],
        "hands": [
            ["PASS"],
            ["PASS"],
            ["PASS"],
            ["PASS"],
            ["PASS"],
            ["PASS"],
            ["PASS"],
            ["PASS"],
            ["SOUTH"],
            ["PASS"],
            ["PASS"],
            ["PASS"],
            ["PASS"],
            ["PASS"],
        ],
        "market": [],
    },
}
