[project]
name = "jeremy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kaggle-environments>=1.32.6",
    "pyarrow>=25.0.1",
    "pytest>=9.1.1",
    "ruff>=0.16.5",
]

[project.optional-dependencies]
local = [
    "torch[device-gfx1101]==2.12.0+rocm7.14.0",
    "rocm[libraries,device-gfx1101]==7.14.0",
]

[[tool.uv.index]]
name = "amd-rocm"
url = "https://repo.amd.com/rocm/whl-multi-arch/"
explicit = true

[tool.uv.sources]
torch = { index = "amd-rocm" }
rocm = { index = "amd-rocm" }
