"""
Build standalone Kaggle submission.py by combining agent and environment modules.

Usage
-----
python src/utils/build_submission.py

Output
------
submission.py
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC_DIR = ROOT / "src"
OUTPUT = ROOT / "submission.py"

MODULES = [
    "environment/state.py",
    "environment/board.py",
    "environment/actions.py",
    "environment/economy.py",
    "environment/market.py",
    "agent/search.py",
    "agent/scheduler.py",
    "agent/planner.py",
    "main.py",
]

HEADER = """\
# ==========================================================
# AUTO GENERATED FILE
# Generated by src/utils/build_submission.py
# Do not edit manually.
# ==========================================================
"""

INTERNAL_PACKAGES = {"agent", "environment", "src", "main"}
INTERNAL_MODULES = {Path(m).stem for m in MODULES} | INTERNAL_PACKAGES


def is_internal_import(module_name: str) -> bool:
    """Check if an imported module belongs to internal agent/environment code."""
    root_pkg = module_name.split(".")[0].strip()
    return root_pkg in INTERNAL_MODULES


def clean_source(text: str) -> tuple[list[str], list[str]]:
    """Separate external imports from module body and remove internal imports."""
    imports = []
    body = []

    for line in text.splitlines():
        # Match 'from <module> import ...'
        if line.startswith("from "):
            m = re.match(r"from\s+([a-zA-Z0-9_.]+)\s+import", line)
            if m and is_internal_import(m.group(1)):
                continue
            imports.append(line)
            continue

        # Match 'import <module>'
        if line.startswith("import "):
            m = re.match(r"import\s+([a-zA-Z0-9_.]+)", line)
            if m and is_internal_import(m.group(1)):
                continue
            imports.append(line)
            continue

        body.append(line)

    return imports, body


def build_submission() -> Path:
    """Combine modular source files into a single standalone submission.py."""
    all_imports = []
    all_body = []
    seen_imports = set()

    for module_rel in MODULES:
        path = SRC_DIR / module_rel
        if not path.exists():
            raise FileNotFoundError(f"Required module not found: {path}")

        text = path.read_text(encoding="utf-8")
        imports, body = clean_source(text)

        for imp in imports:
            if imp not in seen_imports:
                seen_imports.add(imp)
                all_imports.append(imp)

        all_body.append(f"\n# ===================== {module_rel} =====================\n")
        all_body.extend(body)

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT.open("w", encoding="utf-8") as f:
        f.write(HEADER + "\n")
        for imp in sorted(all_imports):
            f.write(imp + "\n")
        f.write("\n")
        for line in all_body:
            f.write(line + "\n")

    print(f"  Output Submission : {OUTPUT}")
    print(f"  Submission Size   : {OUTPUT.stat().st_size:,} bytes")
    return OUTPUT


if __name__ == "__main__":
    build_submission()

