"""
Build standalone Kaggle submission.py by combining agent and environment modules.

Usage
-----
python scripts/build_submission.py --build
python scripts/build_submission.py --bundle

Output
------
submission.py / submission.tar.gz
"""

import argparse
import re
import tarfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT / "src"
OUTPUT = ROOT / ".out" / "submission.py"
OUTPUT_TAR = ROOT / ".out" / "submission.tar.gz"

FILES = [
    "agent",
    "environment",
    "main.py",
]


MODULES = [
    "environment/state.py",
    "environment/board.py",
    "environment/actions.py",
    "environment/economy.py",
    "environment/market.py",
    "agent/config.py",
    "agent/search.py",
    "agent/heuristics/scores.py",
    "agent/heuristics/market.py",
    "agent/heuristics/expansion.py",
    "agent/scheduler.py",
    "agent/jobs.py",
    "agent/planner.py",
    "main.py",
]


HEADER = """\
# ==========================================================
# AUTO GENERATED FILE
# Generated by scripts/build_submission.py
# Do not edit manually.
# ==========================================================
"""

INTERNAL_PACKAGES = {"agent", "environment", "src", "main"}
INTERNAL_MODULES = {Path(m).stem for m in MODULES} | INTERNAL_PACKAGES


def is_internal_import(module_name: str) -> bool:
    """Check if an imported module belongs to internal agent/environment code."""
    root_pkg = module_name.split(".")[0].strip()
    return root_pkg in INTERNAL_MODULES


def clean_source(
    text: str,
) -> tuple[dict[str, set[str]], set[str], list[str]]:
    """Separate external imports from module body and remove internal imports."""
    from_imports: dict[str, set[str]] = {}
    direct_imports: set[str] = set()
    body: list[str] = []

    lines = iter(text.splitlines())
    for line in lines:
        if line.startswith("from ") or line.startswith("import "):
            statement = line
            if "(" in statement and ")" not in statement:
                for next_line in lines:
                    statement += " " + next_line.strip()
                    if ")" in next_line:
                        break

            clean_stmt = re.sub(r"[()]", "", statement.split("#")[0]).strip()

            if m := re.match(r"from\s+([\w.]+)\s+import\s+(.+)", clean_stmt):
                mod_name, names_str = m.group(1), m.group(2)
                if not is_internal_import(mod_name):
                    names = [
                        n.strip() for n in names_str.split(",") if n.strip()
                    ]
                    from_imports.setdefault(mod_name, set()).update(names)
                continue

            if m := re.match(r"import\s+(.+)", clean_stmt):
                for item in m.group(1).split(","):
                    item = item.strip()
                    if item and not is_internal_import(item):
                        direct_imports.add(f"import {item}")
                continue

        body.append(line)

    return from_imports, direct_imports, body


def build_submission() -> Path:
    """Combine modular source files into a single standalone submission.py."""
    all_from_imports: dict[str, set[str]] = {}
    all_direct_imports: set[str] = set()
    all_body = []

    for module_rel in MODULES:
        path = SRC_DIR / module_rel
        if not path.exists():
            raise FileNotFoundError(f"Required module not found: {path}")

        text = path.read_text(encoding="utf-8")
        from_imps, direct_imps, body = clean_source(text)

        for mod, names in from_imps.items():
            all_from_imports.setdefault(mod, set()).update(names)
        all_direct_imports.update(direct_imps)

        all_body.append(
            f"\n# ===================== {module_rel} =====================\n"
        )
        all_body.extend(body)

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT.open("w", encoding="utf-8") as f:
        f.write(HEADER + "\n")
        for imp in sorted(all_direct_imports):
            f.write(imp + "\n")
        for mod in sorted(all_from_imports.keys()):
            names_str = ", ".join(sorted(all_from_imports[mod]))
            f.write(f"from {mod} import {names_str}\n")
        f.write("\n")
        for line in all_body:
            f.write(line + "\n")

    print(f"  Output Submission : {OUTPUT}")
    print(f"  Submission Size   : {OUTPUT.stat().st_size:,} bytes")
    return OUTPUT


def bundle_submission() -> None:
    """Build submission.tar.gz."""
    OUTPUT_TAR.parent.mkdir(parents=True, exist_ok=True)
    with tarfile.open(OUTPUT_TAR, "w:gz") as tar:
        for file in FILES:
            path = SRC_DIR / file
            if path.exists():
                tar.add(
                    path,
                    arcname=file,
                    filter=lambda ti: None if "__pycache__" in ti.name else ti,
                )

    print(f"  Output Archive : {OUTPUT_TAR}")
    print(f"  Created        : {OUTPUT_TAR.stat().st_mtime}")
    print(f"  Archive Size   : {OUTPUT_TAR.stat().st_size:,} bytes")


if __name__ == "__main__":
    args = argparse.ArgumentParser()

    args.add_argument(
        "--build",
        action="store_true",
        help="Build submission.py from agent and environment modules",
    )
    args.add_argument(
        "--bundle",
        action="store_true",
        help="Bundle agent source files into submission.tar.gz",
    )

    parsed_args = args.parse_args()

    if parsed_args.build:
        build_submission()
    if parsed_args.bundle:
        bundle_submission()
