"""
Build standalone Kaggle submission.py by combining agent and environment modules.

Usage
-----
python scripts/build_submission.py --build
python scripts/build_submission.py --bundle

Output
------
submission.py / submission.tar.gz
"""

import argparse
import re
import shutil
import subprocess
import tarfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT / "src"
OUTPUT = ROOT / ".out" / "submission.py"
OUTPUT_TAR = ROOT / ".out" / "submission.tar.gz"

FILES = [
    "main.py",
    "dispatcher.py",
    "environment/board.py",
    "environment/state.py",
    "environment/__init__.py",
    "model/constants.py",
    "model/encoder.py",
    "model/policy.py",
    "model/model_weights.npz",
    "model/__init__.py",
    "strategies/clone_detector.py",
    "strategies/debt_manager.py",
    "strategies/explosion.py",
    "strategies/market_maker.py",
    "strategies/predation.py",
    "strategies/procurement.py",
    "strategies/weed_repair.py",
    "strategies/__init__.py",
    "__init__.py",
]

MODULES = [
    "environment/board.py",
    "environment/state.py",
    "model/constants.py",
    "model/encoder.py",
    "model/policy.py",
    "strategies/clone_detector.py",
    "strategies/debt_manager.py",
    "strategies/explosion.py",
    "strategies/market_maker.py",
    "strategies/predation.py",
    "strategies/procurement.py",
    "strategies/weed_repair.py",
    "dispatcher.py",
    "main.py",
]


HEADER = """\
# ==========================================================
# AUTO GENERATED FILE
# Generated by scripts/build_submission.py
# Do not edit manually.
# ==========================================================
"""

INTERNAL_PACKAGES = {
    "src",
    "main",
    "environment",
    "board",
    "state",
    "dispatcher",
    "model",
    "constants",
    "encoder",
    "policy",
    "strategies",
    "clone_detector",
    "debt_manager",
    "explosion",
    "market_maker",
    "predation",
    "procurement",
    "weed_repair",
}
INTERNAL_MODULES = (
    {Path(m).stem for m in MODULES}
    | {m.replace("/", ".").removesuffix(".py") for m in MODULES}
    | INTERNAL_PACKAGES
)


def is_internal_import(module_name: str) -> bool:
    """Check if an imported module belongs to internal agent/environment code."""
    root_pkg = module_name.split(".")[0].strip()
    return (
        root_pkg in INTERNAL_MODULES or module_name.strip() in INTERNAL_MODULES
    )


def clean_source(
    text: str,
) -> tuple[dict[str, set[str]], set[str], list[str]]:
    """Separate external imports from module body and remove internal imports."""
    from_imports: dict[str, set[str]] = {}
    direct_imports: set[str] = set()
    body: list[str] = []

    raw_lines = text.splitlines()
    i = 0
    n = len(raw_lines)

    while i < n:
        line = raw_lines[i]

        if line.startswith("__all__"):
            if "[" in line and "]" not in line:
                i += 1
                while i < n and "]" not in raw_lines[i]:
                    i += 1
            elif "(" in line and ")" not in line:
                i += 1
                while i < n and ")" not in raw_lines[i]:
                    i += 1
            i += 1
            continue

        if line.startswith("if TYPE_CHECKING:"):
            i += 1
            while i < n and (
                raw_lines[i].startswith("    ")
                or raw_lines[i].startswith("\t")
                or not raw_lines[i].strip()
            ):
                i += 1
            continue

        if line.startswith("from ") or line.startswith("import "):
            statement = line
            if "(" in statement and ")" not in statement:
                i += 1
                while i < n:
                    statement += " " + raw_lines[i].strip()
                    if ")" in raw_lines[i]:
                        break
                    i += 1

            clean_stmt = re.sub(r"[()]", "", statement.split("#")[0]).strip()

            if m := re.match(r"from\s+([\w.]+)\s+import\s+(.+)", clean_stmt):
                mod_name, names_str = m.group(1), m.group(2)
                if not is_internal_import(mod_name):
                    names = [
                        n.strip() for n in names_str.split(",") if n.strip()
                    ]
                    from_imports.setdefault(mod_name, set()).update(names)
                i += 1
                continue

            if m := re.match(r"import\s+(.+)", clean_stmt):
                for item in m.group(1).split(","):
                    item = item.strip()
                    if item and not is_internal_import(item):
                        direct_imports.add(f"import {item}")
                i += 1
                continue

        body.append(line)
        i += 1

    return from_imports, direct_imports, body


def format_with_ruff(file_path: Path) -> None:
    """Format and fix lint issues in generated file."""
    cmd = ["ruff"] if shutil.which("ruff") else ["uvx", "ruff"]

    subprocess.run(
        [*cmd, "check", "--fix", str(file_path)], capture_output=True
    )
    subprocess.run([*cmd, "format", str(file_path)], capture_output=True)

    print("  Formatted with ruff")


def submit_to_kaggle(submission_path: Path) -> None:
    """Submit the generated submission.py to Kaggle."""
    if not shutil.which("kaggle"):
        print("Kaggle CLI not found. Please install it to submit.")
        return

    cmd = [
        "kaggle",
        "competitions",
        "submit",
        "-c",
        "kaggriculture",
        "-f",
        str(submission_path),
        "-m",
        "Automated submission from build_submission.py",
    ]

    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode == 0:
        print("  Submission successful!")
    else:
        print("  Submission failed:")
        print(f"  Error: {result.stderr}")


def build_submission() -> Path:
    """Combine modular source files into a single standalone submission.py."""
    all_from_imports: dict[str, set[str]] = {}
    all_direct_imports: set[str] = set()
    all_body = []

    for module_rel in MODULES:
        path = SRC_DIR / module_rel
        if not path.exists():
            raise FileNotFoundError(f"Required module not found: {path}")

        text = path.read_text(encoding="utf-8")
        from_imps, direct_imps, body = clean_source(text)

        for mod, names in from_imps.items():
            all_from_imports.setdefault(mod, set()).update(names)
        all_direct_imports.update(direct_imps)

        all_body.append(
            f"\n# ===================== {module_rel} =====================\n"
        )
        all_body.extend(body)

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT.open("w", encoding="utf-8") as f:
        f.write(HEADER + "\n")
        for imp in sorted(all_direct_imports):
            f.write(imp + "\n")
        for mod in sorted(all_from_imports.keys()):
            names_str = ", ".join(sorted(all_from_imports[mod]))
            f.write(f"from {mod} import {names_str}\n")
        f.write("\n")
        for line in all_body:
            f.write(line + "\n")

    format_with_ruff(OUTPUT)

    print(f"  Output Submission : {OUTPUT}")
    print(f"  Submission Size   : {OUTPUT.stat().st_size:,} bytes")
    return OUTPUT


def bundle_submission() -> None:
    """Build submission.tar.gz."""
    OUTPUT_TAR.parent.mkdir(parents=True, exist_ok=True)
    with tarfile.open(OUTPUT_TAR, "w:gz") as tar:
        for file in FILES:
            path = SRC_DIR / file
            if path.exists():
                tar.add(
                    path,
                    arcname=file,
                    filter=lambda ti: None if "__pycache__" in ti.name else ti,
                )

    print(f"  Output Archive : {OUTPUT_TAR}")
    print(f"  Created        : {OUTPUT_TAR.stat().st_mtime}")
    print(f"  Archive Size   : {OUTPUT_TAR.stat().st_size:,} bytes")


if __name__ == "__main__":
    args = argparse.ArgumentParser()

    args.add_argument(
        "--build",
        action="store_true",
        help="Build submission.py from agent and environment modules",
    )
    args.add_argument(
        "--bundle",
        action="store_true",
        help="Bundle agent source files into submission.tar.gz",
    )
    args.add_argument(
        "--submit",
        action="store_true",
        help="Submit the generated submission.py to Kaggle",
    )

    parsed_args = args.parse_args()

    if parsed_args.submit and parsed_args.build:
        submission_path = build_submission()
        submit_to_kaggle(submission_path)
    elif parsed_args.build:
        build_submission()
    elif parsed_args.bundle:
        bundle_submission()
    elif parsed_args.submit:
        print("Submitting to Kaggle requires --build to be specified.")
        print("Please run with --build first to generate submission.py.")
    elif not (parsed_args.build or parsed_args.bundle or parsed_args.submit):
        print("No action specified. Use --build, --bundle, or --submit.")
